version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: skin_lesion_db
    environment:
      POSTGRES_DB: skin_lesion_db
      POSTGRES_USER: medical_user
      POSTGRES_PASSWORD: secure_password_123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: